Fix -Wtemplate-body compiler error
The errors where:
- error: ‘VK_KHR_EXTERNAL_MEMORY_WIN32_EXTENSION_NAME’ was not declared in this scope; did you mean ‘VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME’?
The VK_KHR_EXTERNAL_MEMORY_WIN32_EXTENSION_NAME is never available on
linux, so we just never try to add it on that platform.

- error: ‘::glfwGetWin32Window’ has not been declared; did you mean ‘glfwGetWindowPos’?
::glfwGetWin32Window is never available on linux so we just do like the
others examples.